import GeneratorPage from "@/components/generator/GeneratorPage";

export const metadata = {
  title: "Generating README — README Generator",
  description: "Your README is being generated by AI.",
};

export default function GeneratePage() {
  return <GeneratorPage />;
}
