import { Calendar, ExternalLink, Sparkles } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

interface ReadmeInfoProps {
  projectName?: string;
  isLoading?: boolean;
}

export default function ReadmeInfo({
  projectName,
  // isLoading,
}: ReadmeInfoProps) {
  const data = new Date();
  const date = data.toLocaleDateString();

  const [githubLink, setGithubLink] = useState("https://github.com");

  useEffect(() => {
    const githubLink = localStorage.getItem("githubLink");
    if (githubLink) {
      setGithubLink(githubLink);
    }
  }, []);

  // if (isLoading) {
  //   return (
  //     <div className="animate-pulse">
  //       <div className="flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-8">
  //         {/* Shimmer AI badge */}
  //         <div className="relative inline-flex items-center px-3 py-1 rounded-full bg-gray-200 h-8 w-32">
  //           <div className="absolute inset-0 bg-gradient-to-r from-gray-200 via-gray-100 to-gray-200 animate-shimmer bg-[length:200%_100%] rounded-full"></div>
  //         </div>

  //         <div className="flex flex-col sm:flex-row gap-3 sm:gap-8">
  //           {/* Shimmer Repo Link */}
  //           <div className="flex items-center gap-2">
  //             <div className="h-4 w-4 bg-gray-200 rounded"></div>
  //             <div className="h-4 w-24 bg-gray-200 rounded"></div>
  //           </div>

  //           {/* Shimmer Date */}
  //           <div className="flex items-center gap-2">
  //             <div className="h-4 w-4 bg-gray-200 rounded"></div>
  //             <div className="h-4 w-16 bg-gray-200 rounded"></div>
  //           </div>
  //         </div>
  //       </div>

  //       {/* Shimmer Project Name */}
  //       <div className="mt-4">
  //         <div className="h-8 sm:h-12 w-full max-w-xs sm:max-w-none bg-gradient-to-r from-gray-200 via-gray-100 to-gray-200 animate-shimmer bg-[length:200%_100%] rounded-lg"></div>
  //       </div>

  //       <style jsx>{`
  //         @keyframes shimmer {
  //           0% {
  //             background-position: -200% 0;
  //           }
  //           100% {
  //             background-position: 200% 0;
  //           }
  //         }
  //         .animate-shimmer {
  //           animation: shimmer 2s infinite;
  //         }
  //       `}</style>
  //     </div>
  //   );
  // }

  return (
    <div>
      {/* top right corner */}
      <div className="flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-8">
        {/* Generated by ai badge */}
        <div className="relative inline-flex items-center px-3 py-1 rounded-full border border-rose-300 shadow-md bg-white/50 backdrop-blur-sm shadow-rose-100 w-fit">
          <Sparkles className="h-4 w-4 text-rose-500 animate-[pingSlow_2s_infinite]" />
          <span className="ml-2 text-sm bg-gradient-to-r from-rose-600 to-pink-600 bg-clip-text text-transparent">
            AI Generated
          </span>

          {/* Shine effect */}
          <div
            className="absolute top-0 left-0 w-1/2 h-full 
            bg-gradient-to-r from-transparent via-white/40 to-transparent 
            skew-x-[-20deg] animate-[shine_2s_infinite] pointer-events-none"
          ></div>
        </div>

        <div className="flex flex-col sm:flex-row gap-3 sm:gap-8">
          {/* Repo Link */}
          <Link href={githubLink} target="_blank">
            <div className="flex items-center gap-2">
              <ExternalLink className="h-4 w-4 text-rose-500" />
              <p className="text-sm text-gray-600">
                <span className="sm:hidden">Repository</span>
                <span className="hidden sm:inline">Visit Repository</span>
              </p>
            </div>
          </Link>

          {/* Date */}
          <div className="flex items-center gap-2">
            <Calendar className="h-4 w-4 text-rose-500" />
            <p className="text-sm text-gray-600">{date}</p>
          </div>
        </div>
      </div>

      {/* Project Name */}
      {projectName && (
        <div className="mt-4">
          <h1 className="text-xl sm:text-2xl lg:text-4xl font-bold break-words">
            <span className="bg-linear-to-r from-rose-500 to-orange-600 bg-clip-text text-transparent">
              {projectName}
            </span>
          </h1>
        </div>
      )}
    </div>
  );
}
